export const SET_FLIGHTS = 'SET_FLIGHTS';
export const FETCH_FLIGHTS_FAILED = 'FETCH_FLIGHTS_FAILED';

export const PASSENGER_DATA_START = 'PASSENGER_DATA_START';
export const PASSENGER_DATA_SUCCESS = 'PASSENGER_DATA_SUCCESS';
export const PASSENGER_DATA_FAIL = 'PASSENGER_DATA_FAIL';
export const SET_PASSENGER_DATA = 'SET_PASSENGER_DATA'

export const FETCH_PASSENGER_DATA_START = 'FETCH_PASSENGER_DATA_START';
export const FETCH_PASSENGER_DATA_SUCCESS = 'FETCH_PASSENGER_DATA_SUCCESS';
export const FETCH_PASSENGER_DATA_FAIL = 'FETCH_PASSENGER_DATA_FAIL';

export const UPDATE_SEAT_START = 'UPDATE_SEAT_START';
export const UPDATE_SEAT_SUCCESS = 'UPDATE_SEAT_SUCCESS';
export const UPDATE_SEAT_FAIL = 'UPDATE_SEAT_FAIL';

export const DELETE_PASSENGER_START = 'DELETE_PASSENGER_START';
export const DELETE_PASSENGER_SUCCESS = 'DELETE_PASSENGER_SUCCESS';
export const DELETE_PASSENGER_FAIL = 'DELETE_PASSENGER_FAIL';

export const UPDATE_PASSENGER_START = 'UPDATE_PASSENGER_START';
export const UPDATE_PASSENGER_SUCCESS = 'UPDATE_PASSENGER_SUCCESS';
export const UPDATE_PASSENGER_FAIL = 'UPDATE_PASSENGER_FAIL';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

// export const FETCH_ADMIN_MAIL_START = 'FETCH_ADMIN_MAIL_START';
// export const FETCH_ADMIN_MAIL_SUCCESS = 'FETCH_ADMIN_MAIL_SUCCESS';
// export const FETCH_ADMIN_MAIL_FAIL = 'FETCH_ADMIN_MAIL_FAIL';

// export const FETCH_STAFF_MAIL_START = 'FETCH_STAFF_MAIL_START';
// export const FETCH_STAFF_MAIL_SUCCESS = 'FETCH_STAFF_MAIL_SUCCESS';
// export const FETCH_STAFF_MAIL_FAIL = 'FETCH_ADMIN_MAIL_FAIL';

export  const FETCH_MAIL_ID = 'FETCH_MAIL_ID';